version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: terrain-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: terrain-db
    environment:
      MYSQL_ROOT_DATABASE: terrain_booking_db
      MYSQL_ROOT_USER: navin
      MYSQL_ROOT_PASSWORD: navin@1234
      MYSQL_PASSWORD: navin@1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
